server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
  client:
    #表示是否将自己注册进Eureka服务默认为true
    register-with-eureka: true
    #true 表示是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须为true才能配合ribbn使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   # 集群版
#      defaultZone: http://eureka7001.com:7001/eureka/    #单机版